<?php

namespace DoctrineProxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EReservation extends \AppORM\Entity\EReservation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null, 16],
        "\0".parent::class."\0".'hours' => [parent::class, 'hours', null, 16],
        "\0".parent::class."\0".'idReservation' => [parent::class, 'idReservation', null, 16],
        "\0".parent::class."\0".'nameReservation' => [parent::class, 'nameReservation', null, 16],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null, 16],
        "\0".parent::class."\0".'peopleNum' => [parent::class, 'peopleNum', null, 16],
        "\0".parent::class."\0".'table' => [parent::class, 'table', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'date' => [parent::class, 'date', null, 16],
        'hours' => [parent::class, 'hours', null, 16],
        'idReservation' => [parent::class, 'idReservation', null, 16],
        'nameReservation' => [parent::class, 'nameReservation', null, 16],
        'note' => [parent::class, 'note', null, 16],
        'peopleNum' => [parent::class, 'peopleNum', null, 16],
        'table' => [parent::class, 'table', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
