<?php

namespace DoctrineProxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EAdminResponse extends \AppORM\Entity\EAdminResponse implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'admin' => [parent::class, 'admin', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'responseDate' => [parent::class, 'responseDate', null, 16],
        "\0".parent::class."\0".'responseText' => [parent::class, 'responseText', null, 16],
        "\0".parent::class."\0".'userReviews' => [parent::class, 'userReviews', null, 16],
        'admin' => [parent::class, 'admin', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'responseDate' => [parent::class, 'responseDate', null, 16],
        'responseText' => [parent::class, 'responseText', null, 16],
        'userReviews' => [parent::class, 'userReviews', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
