<?php

namespace DoctrineProxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EClient extends \AppORM\Entity\EClient implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'birthDate' => [parent::class, 'birthDate', null, 8],
        "\0".'*'."\0".'email' => [parent::class, 'email', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'name' => [parent::class, 'name', null, 8],
        "\0".'*'."\0".'password' => [parent::class, 'password', null, 8],
        "\0".'*'."\0".'phonenumber' => [parent::class, 'phonenumber', null, 8],
        "\0".'*'."\0".'surname' => [parent::class, 'surname', null, 8],
        "\0".parent::class."\0".'creditCards' => [parent::class, 'creditCards', null, 16],
        "\0".parent::class."\0".'loyaltyPoints' => [parent::class, 'loyaltyPoints', null, 16],
        "\0".parent::class."\0".'nickname' => [parent::class, 'nickname', null, 16],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null, 16],
        "\0".parent::class."\0".'receivesNotifications' => [parent::class, 'receivesNotifications', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'reviews' => [parent::class, 'reviews', null, 16],
        'birthDate' => [parent::class, 'birthDate', null, 8],
        'creditCards' => [parent::class, 'creditCards', null, 16],
        'email' => [parent::class, 'email', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'loyaltyPoints' => [parent::class, 'loyaltyPoints', null, 16],
        'name' => [parent::class, 'name', null, 8],
        'nickname' => [parent::class, 'nickname', null, 16],
        'orders' => [parent::class, 'orders', null, 16],
        'password' => [parent::class, 'password', null, 8],
        'phonenumber' => [parent::class, 'phonenumber', null, 8],
        'receivesNotifications' => [parent::class, 'receivesNotifications', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'reviews' => [parent::class, 'reviews', null, 16],
        'surname' => [parent::class, 'surname', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
