<?php

namespace DoctrineProxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ECreditCard extends \AppORM\Entity\ECreditCard implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cardHolderName' => [parent::class, 'cardHolderName', null, 16],
        "\0".parent::class."\0".'cardName' => [parent::class, 'cardName', null, 16],
        "\0".parent::class."\0".'cardNumber' => [parent::class, 'cardNumber', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'cvv' => [parent::class, 'cvv', null, 16],
        "\0".parent::class."\0".'expirationDate' => [parent::class, 'expirationDate', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        'cardHolderName' => [parent::class, 'cardHolderName', null, 16],
        'cardName' => [parent::class, 'cardName', null, 16],
        'cardNumber' => [parent::class, 'cardNumber', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'cvv' => [parent::class, 'cvv', null, 16],
        'expirationDate' => [parent::class, 'expirationDate', null, 16],
        'id' => [parent::class, 'id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
