<?php

namespace DoctrineProxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ETable extends \AppORM\Entity\ETable implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'idTable' => [parent::class, 'idTable', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'restaurantHall' => [parent::class, 'restaurantHall', null, 16],
        "\0".parent::class."\0".'seatsNumber' => [parent::class, 'seatsNumber', null, 16],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null, 16],
        'idTable' => [parent::class, 'idTable', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'restaurantHall' => [parent::class, 'restaurantHall', null, 16],
        'seatsNumber' => [parent::class, 'seatsNumber', null, 16],
        'state' => [parent::class, 'state', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
