<?php

namespace AppORM\Proxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ERestaurantHall extends \AppORM\Entity\ERestaurantHall implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'idHall' => [parent::class, 'idHall', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'tables' => [parent::class, 'tables', null, 16],
        "\0".parent::class."\0".'totalPlaces' => [parent::class, 'totalPlaces', null, 16],
        "\0".parent::class."\0".'turns' => [parent::class, 'turns', null, 16],
        "\0".parent::class."\0".'waiters' => [parent::class, 'waiters', null, 16],
        'idHall' => [parent::class, 'idHall', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'tables' => [parent::class, 'tables', null, 16],
        'totalPlaces' => [parent::class, 'totalPlaces', null, 16],
        'turns' => [parent::class, 'turns', null, 16],
        'waiters' => [parent::class, 'waiters', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
