<?php

namespace AppORM\Proxies\__CG__\AppORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EUserReview extends \AppORM\Entity\EUserReview implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adminResponses' => [parent::class, 'adminResponses', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'reviewDate' => [parent::class, 'reviewDate', null, 16],
        'adminResponses' => [parent::class, 'adminResponses', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'comment' => [parent::class, 'comment', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'reviewDate' => [parent::class, 'reviewDate', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
